spring.application.name=elastic_search_demo
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.connection-timeout=30s
spring.elasticsearch.socket-timeout=120s

spring.datasource.url=jdbc:postgresql://localhost:5434/products_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=10000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

spring.data.elasticsearch.repositories.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
